export const DEGREE_TYPES = [
  "Associate of Arts (AA)",
  "Associate of Science (AS)",
  "Associate of Applied Science (AAS)",
  "Bachelor of Arts (BA)",
  "Bachelor of Science (BS)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Engineering (BE)",
  "Bachelor of Laws (LLB)",
  "Bachelor of Education (BEd)",
  "Bachelor of Architecture (BArch)",
  "Bachelor of Nursing (BN/BSN)",
  "Master of Arts (MA)",
  "Master of Science (MS)",
  "Master of Business Administration (MBA)",
  "Master of Fine Arts (MFA)",
  "Master of Education (MEd)",
  "Master of Engineering (MEng)",
  "Master of Laws (LLM)",
  "Master of Public Health (MPH)",
  "Master of Social Work (MSW)",
  "Master of Architecture (MArch)",
  "Doctor of Philosophy (PhD)",
  "Doctor of Education (EdD)",
  "Doctor of Business Administration (DBA)",
  "Juris Doctor (JD)",
  "Doctor of Medicine (MD)",
  "Doctor of Dental Surgery (DDS)",
  "Doctor of Veterinary Medicine (DVM)",
  "Doctor of Pharmacy (PharmD)"
];
